// flow-typed signature: d20e01d146fb0fca366c0f607719b815
// flow-typed version: <<STUB>>/tiny-test-finder_v^0.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-test-finder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-test-finder' {
  declare function exports(opts?: Object): string[];
}
